// <auto-generated />
namespace FullstackRPG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class teste3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste3));
        
        string IMigrationMetadata.Id
        {
            get { return "202007120144437_teste3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
